//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSL.EverestDispatchingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EverestDispatchingService.IEverestDispatchingService")]
    public interface IEverestDispatchingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEverestDispatchingService/DoWork", ReplyAction="http://tempuri.org/IEverestDispatchingService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEverestDispatchingService/ObtenerSoportes", ReplyAction="http://tempuri.org/IEverestDispatchingService/ObtenerSoportesResponse")]
        System.Data.DataSet ObtenerSoportes(int p_cod_pais);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IEverestDispatchingServiceChannel : MSL.EverestDispatchingService.IEverestDispatchingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class EverestDispatchingServiceClient : System.ServiceModel.ClientBase<MSL.EverestDispatchingService.IEverestDispatchingService>, MSL.EverestDispatchingService.IEverestDispatchingService {
        
        public EverestDispatchingServiceClient() {
        }
        
        public EverestDispatchingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EverestDispatchingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EverestDispatchingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EverestDispatchingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Data.DataSet ObtenerSoportes(int p_cod_pais) {
            return base.Channel.ObtenerSoportes(p_cod_pais);
        }
    }
}
